# Generated by Django 5.2.1 on 2025-06-03 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "preparation_instructions",
                    models.TextField(
                        blank=True, verbose_name="Preparation Instructions"
                    ),
                ),
                (
                    "turnaround_time",
                    models.PositiveIntegerField(verbose_name="Turnaround Time (hours)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Lab Test Type",
                "verbose_name_plural": "Lab Test Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        upload_to="lab_reports/", verbose_name="Report File"
                    ),
                ),
                ("results", models.TextField(verbose_name="Results")),
                (
                    "reference_range",
                    models.TextField(blank=True, verbose_name="Reference Range"),
                ),
                (
                    "interpretation",
                    models.TextField(blank=True, verbose_name="Interpretation"),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, verbose_name="Abnormal Results"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Report",
                "verbose_name_plural": "Lab Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabTestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="lab_attachments/", verbose_name="File"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="lab.labreport",
                        verbose_name="Report",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Test Attachment",
                "verbose_name_plural": "Lab Test Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabTestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(blank=True, verbose_name="Clinical Notes"),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request Date"
                    ),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="Scheduled Date")),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "requesting_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requesting Doctor",
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lab.labtesttype",
                        verbose_name="Test Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Test Request",
                "verbose_name_plural": "Lab Test Requests",
                "ordering": ["-request_date"],
            },
        ),
        migrations.AddField(
            model_name="labreport",
            name="test_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="lab.labtestrequest",
                verbose_name="Test Request",
            ),
        ),
        migrations.CreateModel(
            name="LabTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(max_length=100, verbose_name="Parameter"),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                ("unit", models.CharField(max_length=20, verbose_name="Unit")),
                (
                    "reference_range",
                    models.CharField(max_length=100, verbose_name="Reference Range"),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, verbose_name="Abnormal"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="lab.labreport",
                    ),
                ),
                (
                    "test_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lab.labtestrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Test Result",
                "verbose_name_plural": "Lab Test Results",
                "ordering": ["parameter"],
            },
        ),
    ]
